feature/KAS-3179 Pub v3: Reports - Basic reports
mdv-professional/publication-report-service pull request #1
Opened 2022-04-07 13:23 UTC by mdv-professional

[KAS-3179](https://kanselarij.atlassian.net/browse/KAS-3179)
---

### Review
[test-frontend-branch](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/tree/feature/KAS-3179-pub-v3--reports--basic--test-view) Hierin is een route `/publicaties/overzicht/rapporten-dev` aangemaakt. Vanaf deze pagina kunt ge een job starten en het rapport downloaden.

### Nog niet gedaan:
- Documentatie van de job-parameters. (zie vraag 4.)
- Keys genereren voor .drone-config. Dit is waarschijnlijk werk voor iemand anders.

### Vragen:
1. Moet er iets van cleanup script runnen om de rapporten terug te verwijderen wanneer ze zijn opgevraagd?
2. Is het OK om te upgraden naar mu-javascript-template met TypeScript en de record-classes in TypeScript te declareren?
3. Voor de documentatie van de job-parameters zou ik ook graag TypeScript gebruiken. Dit lijkt me leesbaarder dan het in markdown te gieten.

2022-04-08 16:39 UTC, ValenberghsSven commented
Ik heb geprobeerd om deze nog te reviewen voor verlof, maar er zit zoveel nieuw in dat ik er niet mee rond zal geraken.
Maar ik kan wel al wat je vragen proberen te beantwoorden.
Vragen:
    1. Is niet gevraagd, zou ik dus ook niet meteen meenemen.
    2+3. Die template is nog maar net nieuw kan dat? (2 dagen geleden 1.6.0 released). Ik heb op zich geen bezwaar op typescript, weet niet hoe de rest erover denkt.
    4. Ik heb de feature en wat er gevraagd is nog niet voldoende bestudeerd om dit te kunnen beantwoorden. 
    5. `cogs` dit refactoren can later nog, ik zie niet direct bezwaar om dat nu al op te lossen.

Suggesties

    1. Zou een job dan zo makkelijk mislukken of kan je mogelijk eerder een leeg rapport maken.

Out of scope

    1. die `fabio` in ander ticket gelijktrekken lijkt me wel een goed plan, niet zeker van de gevolgen, out of scope idd.

2022-04-11 13:04 UTC, MikiDi commented on lib/virtuoso-client.js
> +  if (response.ok) {
Hier ontbreekt nu een negatie denk ik ...

2022-04-11 13:06 UTC, MikiDi commented on lib/virtuoso-client.js
> +import fetch, { Headers } from 'node-fetch';
"query-csv" lijkt me een toepasselijkere naam voor de filename, alsook voor de naam van de methode (`queryCsv`)

2022-04-11 13:08 UTC, MikiDi commented on lib/virtuoso-client.js
> +  await pipeline(response.body, Fs.createWriteStream(downloadPath));
Een streaming aanpak is momenteel een overoptimalisatie. Kan je de signatuur van deze methode dezelfde maken als die van de bestaande `query`-methode (eventueel met een 2e argument om het endpoint te specifiëren dat default het virtuoso endpoint uit de config heeft). De return-waarde is een string.

2022-04-21 12:51 UTC, MikiDi requested changes

2022-04-21 12:51 UTC, MikiDi commented on lib/virtuoso-client.js
> +}
Deze functie willen we wat vereenvoudigen. We willen
- De streaming aanpak weg en in de plaats rechtstreeks de response (een string die de volledige CSV bevat) returnen. Streaming is hier een overoptimalisatie. Ook verandert het het type van de return-waarde tov wat we gewend zijn bij de reguliere `query`, wat de functie moeilijker te begrijpen maakt. De code om de file effectief weg te schrijven wordt verplaatst naar de plaats waar deze functie opgeroepen wordt.
- De signatuur van de functie zo nauw mogelijk laten aanleunen bij de reguliere `query` die we al kennen. Dit wil zeggen: als eerste argument een string met daarin de query. Als 2e argument een string om het endpoint te specifiëren dat default het virtuoso endpoint uit de config heeft.
- Om ook de naam van de functie zo dicht mogelijk te laten aansluiten bij wat we al kennen, de functie hernoemen naar `queryCsv`

Graag ook de naam van de js-file veranderen naar `query-csv.js`.

2022-04-22 08:52 UTC, mdv-professional commented on lib/utils.js
> +}
OK

2022-04-22 08:56 UTC, mdv-professional commented on lib/sparql.js
> +}
Aanpassing gebeurt. Mij helpt die wrapping wel bij het developpen. Ik heb het ook al gezien (zonder `asRoot` parameter) in andere projecten.

2022-04-22 08:57 UTC, mdv-professional commented on lib/virtuoso-client.js
> +}
Gebeurt.

2022-04-25 09:20 UTC, MikiDi approved these changes

2022-04-25 13:04 UTC, merged